/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Background(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./static/background.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="monitor" position={[0, 0, 1.07]}>
          <mesh
            name="bottom_mesh"
            castShadow
            receiveShadow
            geometry={nodes.bottom_mesh.geometry}
            material={nodes.bottom_mesh.material}
            position={[0.01, -0.26, -0.08]}
            scale={[1.37, 0.91, 1.62]}
          />
          <mesh
            name="screen_mesh"
            castShadow
            receiveShadow
            geometry={nodes.screen_mesh.geometry}
            material={nodes.screen_mesh.material}
            position={[0, 0, -1.37]}
            scale={[1, 0.33, 1.17]}
          />
          <mesh
            name="stand_mesh"
            castShadow
            receiveShadow
            geometry={nodes.stand_mesh.geometry}
            material={nodes.stand_mesh.material}
            position={[0, -0.45, -0.86]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-1, -1.92, -1]}
          >
            <mesh
              name="Cube"
              castShadow
              receiveShadow
              geometry={nodes.Cube.geometry}
              material={nodes.Cube.material}
              position={[0, -0.43, -0.13]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[0.03, 0.05, 0.02]}
            />
            <mesh
              name="Cube001"
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={nodes.Cube001.material}
              position={[0, 0.23, -0.13]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[0.03, 0.05, 0.02]}
            />
            <mesh
              name="Cylinder"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder.geometry}
              material={nodes.Cylinder.material}
              position={[0, 0.23, -0.27]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[0.16, 0.07, 0.08]}
            />
            <mesh
              name="Cylinder001"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001.geometry}
              material={nodes.Cylinder001.material}
              position={[0, 0.23, -0.18]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[0.11, 0.03, 0.06]}
            />
          </mesh>
        </group>
        <group
          name="drawer"
          position={[-2.68, 0.83, 1.79]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            name="drawer_surface001"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface001.geometry}
            material={materials.wood}
            position={[0, 0.32, -0.76]}
          />
          <mesh
            name="drawer_surface002"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface002.geometry}
            material={materials.wood}
            position={[0, 0.32, 0.76]}
          />
          <mesh
            name="drawer_surface003"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface003.geometry}
            material={materials.wood}
            position={[-1.13, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface004"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface004.geometry}
            material={materials.wood}
            position={[0.01, 0.04, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="drawer_surface005"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface005.geometry}
            material={materials.wood}
            position={[1.16, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
        <group
          name="drawer001"
          position={[-0.89, 0.83, 1.79]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            name="drawer_surface006"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface006.geometry}
            material={materials.wood}
            position={[1.16, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface007"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface007.geometry}
            material={materials.wood}
            position={[0.01, 0.04, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="drawer_surface008"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface008.geometry}
            material={materials.wood}
            position={[-1.13, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface009"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface009.geometry}
            material={materials.wood}
            position={[0, 0.32, 0.76]}
          />
          <mesh
            name="drawer_surface010"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface010.geometry}
            material={materials.wood}
            position={[0, 0.32, -0.76]}
          />
        </group>
        <group
          name="drawer002"
          position={[0.9, 0.83, 1.79]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            name="drawer_surface011"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface011.geometry}
            material={materials.wood}
            position={[0, 0.32, -0.76]}
          />
          <mesh
            name="drawer_surface012"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface012.geometry}
            material={materials.wood}
            position={[0, 0.32, 0.76]}
          />
          <mesh
            name="drawer_surface013"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface013.geometry}
            material={materials.wood}
            position={[-1.13, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface014"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface014.geometry}
            material={materials.wood}
            position={[0.01, 0.04, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="drawer_surface015"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface015.geometry}
            material={materials.wood}
            position={[1.16, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
        </group>
        <group
          name="drawer003"
          position={[2.69, 0.83, 1.79]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            name="drawer_surface016"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface016.geometry}
            material={materials.wood}
            position={[1.16, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface017"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface017.geometry}
            material={materials.wood}
            position={[0.01, 0.04, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="drawer_surface018"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface018.geometry}
            material={materials.wood}
            position={[-1.13, 0.32, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="drawer_surface019"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface019.geometry}
            material={materials.wood}
            position={[0, 0.32, 0.76]}
          />
          <mesh
            name="drawer_surface020"
            castShadow
            receiveShadow
            geometry={nodes.drawer_surface020.geometry}
            material={materials.wood}
            position={[0, 0.32, -0.76]}
          />
        </group>
        <group name="table_surface" position={[0, 0.52, 1.47]}>
          <mesh
            name="table_surface_mesh"
            castShadow
            receiveShadow
            geometry={nodes.table_surface_mesh.geometry}
            material={nodes.table_surface_mesh.material}
            position={[0, 0, -0.36]}
            scale={[3.67, 1.49, 0.05]}
          />
          <mesh
            name="table_surface_mesh001"
            castShadow
            receiveShadow
            geometry={nodes.table_surface_mesh001.geometry}
            material={nodes.table_surface_mesh001.material}
            position={[0, 0, 0.36]}
            scale={[3.67, 1.49, 0.05]}
          />
          <mesh
            name="table_surface_mesh002"
            castShadow
            receiveShadow
            geometry={nodes.table_surface_mesh002.geometry}
            material={nodes.table_surface_mesh002.material}
            position={[0, -1.44, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[3.67, 0.31, 0.05]}
          />
          <mesh
            name="table_surface_mesh003"
            castShadow
            receiveShadow
            geometry={nodes.table_surface_mesh003.geometry}
            material={nodes.table_surface_mesh003.material}
            position={[3.62, 0, 0]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.49, 0.36, 0.05]}
          />
          <mesh
            name="table_surface_mesh004"
            castShadow
            receiveShadow
            geometry={nodes.table_surface_mesh004.geometry}
            material={nodes.table_surface_mesh004.material}
            position={[-3.63, 0, 0]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.49, 0.36, 0.05]}
          />
        </group>
        <group name="screen" position={[0, 0, 1.07]}>
          <mesh
            name="screen_mesh001"
            castShadow
            receiveShadow
            geometry={nodes.screen_mesh001.geometry}
            material={materials.screen}
            position={[0, 0.02, -1.37]}
            scale={[1, 0.33, 1.17]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./static/background.glb");